version: "3.8"

services:
  db:
    image: postgres
    container_name: paaartay_db
    env_file:
      - ./env/postgres.env
    ports: 
      - "5432:5432"
    volumes:
      - data:/data/db

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-paaartay_localstack}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    env_file:
      - ./env/localstack.env
    environment:
      - AWS_DEFAULT_REGION=us-west-1
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
  api:
    build: .
    container_name: paaartay_api
    env_file:
      - ./env/api.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - localstack

volumes:
  data: