default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: localstack_poc_development

test:
  <<: *default
  database: localstack_poc_test

production:
  <<: *default
  database: localstack_poc_production
